# Generated by Django 2.0.1 on 2018-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
                ('event_title', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('event_infor', models.CharField(max_length=1000)),
            ],
        ),
    ]
