# Generated by Django 2.0.1 on 2018-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_entree'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.CharField(default=11, max_length=1000),
            preserve_default=False,
        ),
    ]
