# Generated by Django 2.0.1 on 2018-01-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=10)),
                ('question_answer', models.CharField(max_length=250)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='entree',
            name='Event',
        ),
        migrations.DeleteModel(
            name='Entree',
        ),
    ]
