# Generated by Django 2.0.1 on 2018-01-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180129_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.CharField(max_length=1000),
        ),
    ]
