# Generated by Django 2.0.1 on 2018-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180130_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
