# Generated by Django 2.0.1 on 2018-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
