# Generated by Django 2.0.1 on 2018-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_questionmultiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmultiple',
            name='question_content',
            field=models.CharField(max_length=1000),
        ),
    ]
