# Generated by Django 2.0.1 on 2018-02-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180204_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionmultiple',
            name='Choice',
        ),
        migrations.AddField(
            model_name='option',
            name='Multiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.QuestionMultiple'),
        ),
    ]
