# Generated by Django 2.0.1 on 2018-02-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180206_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Options',
        ),
    ]
