# Generated by Django 2.0.2 on 2018-02-07 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20180206_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='vendor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonchoicequestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nonchoicequestion',
            name='vendor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
