# Generated by Django 2.0.2 on 2018-02-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180207_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canaddone',
            field=models.BooleanField(default=True),
        ),
    ]
